name: Java CI with Maven

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV

      - name: Install Maven
        run: |
          sudo apt-get install -y maven
          mvn -version

      - name: Maven Clean Install
        run: mvn clean install -U

      - name: Maven Package
        run: mvn package
