name: Java CI with Maven on macOS

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Java and Maven
        run: |
          brew update
          brew install openjdk@11
          brew install maven
          sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
          export JAVA_HOME=$(/usr/libexec/java_home -v 11)
          export PATH="$JAVA_HOME/bin:$PATH"
          java -version
          mvn -version

      - name: Build and install parent POM
        run: |
          cd thunderpay
          mvn clean install

      - name: Build submodules
        run: |
          mvn clean install
