name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up JDK (Temurin distribution for JDK 11 or 17 or Java 23 as needed)
      - name: Set up JDK 23 (or replace with your version)
        uses: actions/setup-java@v4
        with:
          java-version: '11'  # Or 17, or 23 as per your project needs
          distribution: 'temurin'  # You can use 'adoptopenjdk', 'zulu', or 'corretto' as well

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -U
